---
affiliate-marketing:
  team: app
  pagerduty_enabled: false
  slack_channel: alerts-ngi
  alias: app42
  secrets:
  - DB_PASSWORD_CRYPT
  - JENKINS_API_TOKEN
  - SAASQUATCH_API_TOKEN
  - FIREBASE_API_KEY
  - FUNDROCKET_SERVICE_API_TOKEN
