api-auth:
  team: api-platform
  pagerduty_enabled: false
  slack_channel: alerts-api
  alias: app35
  secrets:
  - APIGEE_CLIENT_API_TOKEN
  - DB_PASSWORD_CRYPT
  - FUNNEL_SERVICE_TOKEN
  - LOGGLY_TOKEN
  - USER_SERVICE_API_KEY
  - VAULT_FILE_SERVICE_TOKEN
  glue:
    connections:
      api-auth-service:
        availability_zone: us-west-2c
        engine: postgresql
        port: 5432
        host: api-auth-service-postgres.beta-internal.com
        name: apiauth_db
    crawlers:
      datalake-api-auth-service:
        connection_name: api-auth-service
        include_path: apiauth_db
        exclude_path: []
        trigger: cron(30 04 * * ? *)
    jobs:
      api-auth-service:
        connection_name: api-auth-service
        glue_version: '3.0'
        script_location: s3://womply-datalake-scripts/beta/api_auth_service.py
        python_version: '3'
        number_of_workers: 2
        worker_type: 'G.1X'
        default_arguments:
          --TempDir: s3://womply-datalake-glue-working/beta
          --conf: "spark.yarn.maxAppAttempts=1"
          --extra-py-files: s3://womply-datalake-scripts/beta/python-shell-scripts/Data_Validation.zip,s3://womply-datalake-scripts/beta/python-shell-scripts/datalake-common-lib.zip
          --job-bookmark-option: job-bookmark-disable
          --job-language: python
          --womply_env: beta
          --database_name: glue-catalog-database
          --db_user: datalakebeta
          --additional-python-modules: psycopg2-binary==2.8.5
          --python-modules-installer-option: --upgrade
          --db_password_secret_id: "/apps/glue/jobs/shared/DB_PASSWORD"
    triggers:
      api-auth-service:
        type: ON_DEMAND
        schedule: null
        actions:
        - job_name: api-auth-service
  postgres:
    index: 1
    name: "apiauth_db"
    family: 'postgres11'
    version: '11.12'
    instance_class: 'db.t3.small'
    storage: 100
    apply_immediately: true
    storage_encrypted: true
    performance_insights: true
    backup_period: 7
