---
bizshield:
  team: app
  pagerduty_enabled: false
  slack_channel: alerts-email-platform
  alias: svc27
  glue:
    connections:
      bizshield-service:
        availability_zone: us-west-2b
        engine: postgresql
        port: 5432
        host: preprod-svc27-postgres.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        name: service
    crawlers:
      datalake-bizshield-service:
        connection_name: bizshield-service
        include_path: service
        exclude_path: []
        trigger: cron(30 05 * * ? *)
        table_prefix: 'bizshield_'
    jobs:
      bizshield-service:
        connection_name: bizshield-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/beta/bizshield_service.py
        python_version: 3
        number_of_workers: 10
        worker_type: Standard
        default_arguments:
          --TempDir: s3://womply-datalake-glue-working/beta/
          --conf: "spark.yarn.maxAppAttempts=1"
          --extra-py-files: s3://womply-datalake-scripts/beta/datalake-common-lib.zip
          --job-language: python
          --womply_env: beta
          --database_name: glue-catalog-database
    triggers:
      bizshield-service:
        type: ON_DEMAND
        schedule: null
        actions:
        - job_name: bizshield-service
