---
contact-verification:
  team: data-platform
  pagerduty_enabled: false
  slack_channel: alerts-payments-data
  alias: svc47
  secrets:
  - APPOPTICS_SERVICE_KEY
  - DB_PASSWORD_CRYPT
  - GEOCODIO_API_KEY
  glue:
    connections:
      contact-verification-service:
        name: service
        engine: postgresql
        host: contact-verification-service-postgres.beta-internal.com
        port: 5432
        availability_zone: us-west-2c
    crawlers:
      datalake-contact-verification-service:
        connection_name: contact-verification-service
        include_path: service
        exclude_paths: []
        trigger: 'cron(30 22 * * ? *)'
    jobs:
      contact-verification-service:
        connection_name: contact-verification-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/beta/contact_verification_service.py
        python_version: 3
        worker_type: 'G.1X'
        number_of_workers: 10
        default_arguments:
          --extra-py-files: s3://womply-datalake-scripts/beta/datalake-common-lib.zip
          --TempDir: s3://womply-datalake-glue-working/beta/
          --job-language: python
          --womply_env: beta
          --database_name: glue-catalog-database
          --conf: "spark.yarn.maxAppAttempts=1"
    triggers:
      contact-verification-service:
        type: ON_DEMAND
        schedule: null
        actions:
        - job_name: contact-verification-service
  postgres:
    index: 1
    name: "service"
    root_user: womply
    family: 'postgres11'
    version: '11.12'
    instance_class: 'db.t3.small'
    iops: 1500
    storage: 100
    apply_immediately: true
    storage_encrypted: true
    performance_insights: true
    backup_period: 7
