---
customer-email:
  team: app
  pagerduty_enabled: false
  slack_channel: alerts-email-platform
  alias: svc36
  glue:
    connections:
      customer-email-service:
        name: customeremail_db
        engine: postgresql
        host: psql-customeremail-beta.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        port: 5432
        availability_zone: us-west-2a
    crawlers:
      datalake-customer-email-service:
        connection_name: customer-email-service
        include_path: customeremail_db
        exclude_paths: []
        trigger: 'cron(00 09 * * ? *)'
    jobs:
      customer-email-service:
        connection_name: customer-email-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/beta/customer_email_service.py
        python_version: 3
        worker_type: Standard
        number_of_workers: 10
        default_arguments:
          --extra-py-files: s3://womply-datalake-scripts/beta/datalake-common-lib.zip
          --TempDir: s3://womply-datalake-glue-working/beta/
          --job-language: python
          --womply_env: beta
          --database_name: glue-catalog-database
          --conf: "spark.yarn.maxAppAttempts=1"
    triggers:
      customer-email-service:
        type: ON_DEMAND
        schedule: null
        actions:
        - job_name: customer-email-service
