---
fundrocket:
  team: fin
  pagerduty_enabled: false
  slack_channel: alerts-fin
  alias: app43
  extra-policies:
    athena-data-query-access:
      description: Grants fundrocket-sevice access to athena to query data and metadata
      policy_template: athena_data_query_access.json.tmpl
      params:
        queries:
        - '*'
    s3-fundrocket-read-only:
      description: Grants fundrocket-sevice read-only access to various s3 buckets
      policy_template: s3_read_only.json.tmpl
      params:
        read_only_bucket_paths:
        - womply-reports/app39-womply-pay-service/beta/affiliate_payouts/ppp/*
        - womply-reports/app42-affiliate-marketing-service/beta/affiliate_payouts/ppp/*
    s3-fundrocket-read-write:
      description: Grants fundrocket-sevice read-write access to various s3 buckets
      policy_template: s3_read_write.json.tmpl
      params:
        read_only_bucket_paths:
        - fundrocket-data/stg/*
        - womply-preprod-file-vault/ppp/raw/*
        - womply-preprod-file-vault/pay/raw/*
        read_write_bucket_paths:
        - fundrocket-data/stg/*
        - womply-preprod-file-vault/ppp/raw/*
        - womply-preprod-file-vault/pay/raw/*
    sqs-access:
      description: Grants fundrocket-sevice access to SQS queues
      policy_template: sqs_access.json.tmpl
      params:
        queues:
        - us-east-1:754841671700:stg*
        - us-east-1:754841671700:beta*
  redis-cache:
    instance_type: cache.t3.small
    version: 5.0.6
    parameter_version: redis5.0
  secrets:
  - AFFILIATE_MARKETING_SERVICE_API_TOKEN
  - AUTH0_CLIENT_SECRET
  - AUTH0_MGMT_CLIENT_SECRET
  - DB_CONNECTION
  - DWOLLA_KEY
  - DWOLLA_SECRET
  - EMAIL_SERVICE_API_TOKEN
  - FEESPOTTER_TWILIO_API_KEY
  - FOUNTAINHEAD_AUTH_CODE
  - FOUNTAINHEAD_BANK_ID 
  - FOUNTAINHEAD_HASHED_PASSWORD
  - FUNDINGCIRCLE_AUTH_CODE
  - FUNDINGCIRCLE_BANK_ID
  - FUNDINGCIRCLE_HASHED_PASSWORD
  - LOB_API_KEY
  - MIDDESK_API_KEY
  - NMI_SECURITY_KEY
  - PAY_DWOLLA_KEY
  - PAY_DWOLLA_SECRET
  - PERSONA_API_TOKEN
  - PERSONA_SIGNATURE_KEY
  - PLAID_PUBLIC_KEY
  - PLAID_SECRET
  - SAASQUATCH_API_TOKEN
  - SALESFORCE_PASSWORD
  - SALESFORCE_SECURITY_TOKEN
  - SBA_LOAN_STATUS_API_HARVEST_TOKEN
  - SBA_LOAN_STATUS_API_HARVEST_VENDOR_KEY
  - SENDGRID_API_KEY
  - SENTRY_DSN
  - SIGNUP_SERVICE_API_TOKEN
  - TWILIO_API_KEY
  - USER_SERVICE_API_TOKEN
  - VAULT_FILE_SERVICE_API_TOKEN
  - WOMPLY_PLAID_PUBLIC_KEY
  - WOMPLY_PLAID_SECRET
  - WOMPLY_TEST_HASHED_PASSWORD
  - WOMPLY_TWILIO_API_KEY
  glue:
    connections:
      fundrocket-service:
        availability_zone: us-west-2c
        engine: postgresql
        port: 5432
        host: stg-ro-db-blue.cl4koas41b2p.us-east-1.rds.amazonaws.com
        name: ebdb
    crawlers:
      datalake-fundrocket-service:
        connection_name: fundrocket-service
        include_path: ebdb
        exclude_paths: []
        trigger: null
    jobs:
      fundrocket-service:
        connection_name: fundrocket-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/beta/fundrocket_service.py
        python_version: 3
        number_of_workers: 4
        worker_type: 'G.1X'
        default_arguments:
          --TempDir: s3://womply-datalake-glue-working/beta/
          --conf: "spark.yarn.maxAppAttempts=1"
          --extra-py-files: s3://womply-datalake-scripts/beta/datalake-common-lib.zip
          --job-language: python
          --womply_env: beta
          --db_name: "ebdb"
          --database_name: glue-catalog-database
      fundrocket-service-mca-applications:
        connection_name: fundrocket-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/beta/fin_service_mca_applications.py
        python_version: 3
        number_of_workers: 2
        worker_type: 'G.1X'
        default_arguments:
          --TempDir: s3://womply-datalake-glue-working/beta/
          --conf: "spark.yarn.maxAppAttempts=1"
          --extra-py-files: s3://womply-datalake-scripts/beta/datalake-common-lib.zip
          --job-language: python
          --womply_env: beta
          --db_name: "ebdb"
          --database_name: glue-catalog-database
    triggers:
      fundrocket-service:
        type: ON_DEMAND
        schedule: null
        actions:
        - job_name: fundrocket-service
        - job_name: fundrocket-service-mca-applications

fundrocket-web:
  team: fin
  pagerduty_enabled: false
  slack_channel: d-fin-sentry
  alias: app43
  topics:
    names:
    - soa-payment-transactions

