---
killbill:
  team: app
  pagerduty_enabled: false
  slack_channel: alerts-womply-pay
  alias: svc20
  glue:
    connections:
      killbill-service:
        name: service
        engine: mysql
        host: preprod-svc20-mysql.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        port: 3306
        availability_zone: us-west-2b
    crawlers:
      datalake-killbill-service:
        connection_name: killbill-service
        include_path: service
        exclude_paths: []
        table_prefix: 'killbill_'
        trigger: 'cron(00 12 * * ? *)'
    jobs:
      killbill-service:
        connection_name: killbill-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/beta/killbill.py
        python_version: 3
        worker_type: 'G.1X'
        number_of_workers: 10
        default_arguments:
          --extra-py-files: s3://womply-datalake-scripts/beta/datalake-common-lib.zip
          --TempDir: s3://womply-datalake-glue-working/beta/
          --job-language: python
          --womply_env: beta
          --database_name: glue-catalog-database
          --conf: "spark.yarn.maxAppAttempts=1"
    triggers:
      killbill-service:
        type: ON_DEMAND
        schedule: null
        actions:
        - job_name: killbill-service
