---
product:
  team: app
  pagerduty_enabled: false
  slack_channel: alerts-apps-platform
  alias: svc18
  glue:
    connections:
      product-service:
        name: db_productservice_preprod
        engine: postgresql
        host: db-productservice-preprod.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        port: 5432
        availability_zone: us-west-2c
    crawlers:
      datalake-product-service:
        connection_name: product-service
        include_path: db_productservice_preprod
        exclude_paths: []
        trigger: 'cron(30 10 * * ? *)'
    jobs:
      product-service:
        connection_name: product-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/beta/product_service.py
        python_version: 3
        worker_type: Standard
        number_of_workers: 10
        default_arguments:
          --extra-py-files: s3://womply-datalake-scripts/beta/datalake-common-lib.zip
          --TempDir: s3://womply-datalake-glue-working/beta/
          --job-language: python
          --womply_env: beta
          --database_name: glue-catalog-database
          --conf: "spark.yarn.maxAppAttempts=1"
    triggers:
      product-service:
        type: ON_DEMAND
        schedule: null
        actions:
        - job_name: product-service
