---
storefront-data:
  team: app
  pagerduty_enabled: false
  slack_channel: alerts-storefront
  alias: svc46
  glue:
    connections:
      storefront-data-service:
        availability_zone: us-west-2a
        engine: postgresql
        port: 5432
        host: psql-storefrontdata-beta.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        name: service
    crawlers:
      datalake-storefront-data-service:
        connection_name: storefront-data-service
        include_path: service
        exclude_paths: []
        trigger: 'cron(30 21 * * ? *)'
    jobs:
      storefront-data-service:
        connection_name: storefront-data-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/beta/storefront_data_service.py
        python_version: 3
        number_of_workers: 5
        worker_type: Standard
        default_arguments:
          --TempDir: s3://womply-datalake-glue-working/beta/
          --conf: "spark.yarn.maxAppAttempts=1"
          --extra-py-files: s3://womply-datalake-scripts/beta/datalake-common-lib.zip
          --job-language: python
          --womply_env: beta
          --database_name: glue-catalog-database
    triggers:
      storefront-data-service:
        type: ON_DEMAND
        schedule: null
        actions:
        - job_name: storefront-data-service
