---
subscription:
  team: app
  pagerduty_enabled: false
  slack_channel: alerts-apps-platform
  alias: svc39
  secrets:
  - DB_PASSWORD_CRYPT
  - LOGGLY_TOKEN
  glue:
    connections:
      subscription-service:
        availability_zone: us-west-2c
        engine: postgresql
        port: 5432
        host: subscription-service-postgres.beta
        name: subscription_db
    crawlers:
      datalake-subscription-service:
        connection_name: subscription-service
        include_path: subscription_db
        exclude_paths: []
        trigger: 'cron(30 12 * * ? *)'
    jobs:
      subscription-service:
        connection_name: subscription-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/beta/subscription_service.py
        python_version: 3
        number_of_workers: 5
        worker_type: Standard
        default_arguments:
          --TempDir: s3://womply-datalake-glue-working/beta/
          --conf: "spark.yarn.maxAppAttempts=1"
          --extra-py-files: s3://womply-datalake-scripts/beta/datalake-common-lib.zip
          --job-language: python
          --womply_env: beta
          --database_name: glue-catalog-database
    triggers:
      subscription-service:
        type: ON_DEMAND
        schedule: null
        actions:
        - job_name: subscription-service
  postgres:
    index: 1
    name: 'subscription_db'
    family: 'postgres12'
    version: '12.7'
    instance_class: 'db.t2.small'
    storage: 10
    apply_immediately: true
    storage_encrypted: true
    performance_insights: true
    backup_period: 7
