---
telephony:
  team: app
  pagerduty_enabled: false
  slack_channel: alerts-apps-platform
  alias: svc11
  topics:
    names:
    - soa-twilio-message-status
  glue:
    connections:
      telephony-service:
        availability_zone: us-west-2c
        engine: postgresql
        port: 5432
        host: psql-telephony-beta.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        name: service
    crawlers:
      datalake-telephony-service:
        connection_name: telephony-service
        include_path: service
        exclude_paths: []
        trigger: 'cron(30 12 * * ? *)'
    jobs:
      telephony-service:
        connection_name: telephony-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/beta/telephony_service.py
        python_version: 3
        number_of_workers: 10
        worker_type: 'G.1X'
        default_arguments:
          --TempDir: s3://womply-datalake-glue-working/beta/
          --conf: "spark.yarn.maxAppAttempts=1"
          --extra-py-files: s3://womply-datalake-scripts/beta/datalake-common-lib.zip
          --job-language: python
          --womply_env: beta
          --database_name: glue-catalog-database
    triggers:
      telephony-service:
        type: ON_DEMAND
        schedule: null
        actions:
        - job_name: telephony-service
