---
user:
  team: data-platform
  pagerduty_enabled: false
  slack_channel: alerts-apps-platform
  alias: svc22
  glue:
    connections:
      user-service:
        availability_zone: us-west-2a
        engine: postgresql
        port: 5432
        host: preprod-svc22-postgres.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        name: service
      user-service-delta:
        availability_zone: us-west-2a
        engine: postgresql
        port: 5432
        host: preprod-svc22-postgres.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        name: service
    crawlers:
      datalake-user-service:
        connection_name: user-service
        include_path: service
        exclude_paths: []
        trigger: 'cron(00 07 * * ? *)'
      datalake-user-service-delta:
        connection_name: user-service-delta
        include_path: service
        exclude_paths: []
        trigger: 'cron(00 07 * * ? *)'
    jobs:
      user-service:
        connection_name: user-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/beta/user_service.py
        python_version: 3
        number_of_workers: 10
        worker_type: Standard
        default_arguments:
          --TempDir: s3://womply-datalake-glue-working/beta/
          --conf: "spark.yarn.maxAppAttempts=1"
          --extra-py-files: s3://womply-datalake-scripts/beta/datalake-common-lib.zip
          --job-language: python
          --womply_env: beta
          --database_name: glue-catalog-database
      user-service-delta:
        connection_name: user-service-delta
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/beta/user_service_delta.py
        python_version: 3
        number_of_workers: 10
        worker_type: Standard
        default_arguments:
          --TempDir: s3://womply-datalake-glue-working/beta/
          --conf: "spark.yarn.maxAppAttempts=1"
          --extra-py-files: s3://womply-datalake-scripts/beta/datalake-common-lib.zip
          --job-language: python
          --womply_env: beta
          --database_name: glue-catalog-database
    triggers:
      user-service:
        type: ON_DEMAND
        schedule: null
        actions:
        - job_name: user-service
        - job_name: user-service-delta
