---
website-monitoring:
  team: app
  pagerduty_enabled: false
  slack_channel: alerts-apps-platform
  alias: svc33
  glue:
    connections:
      website-monitoring-service:
        availability_zone: us-west-2c
        engine: postgresql
        port: 5432
        host: psql-webmon-beta.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        name: webmon_db
    crawlers:
      datalake-website-monitoring-service:
        connection_name: website-monitoring-service
        include_path: webmon_db
        exclude_paths: []
        trigger: 'cron(00 06 * * ? *)'
    jobs:
      website-monitoring-service:
        connection_name: website-monitoring-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/beta/webmon_service.py
        python_version: 3
        number_of_workers: 2
        worker_type: 'G.1X'
        default_arguments:
          --TempDir: s3://womply-datalake-glue-working/beta/
          --conf: "spark.yarn.maxAppAttempts=1"
          --extra-py-files: s3://womply-datalake-scripts/beta/datalake-common-lib.zip
          --job-language: python
          --womply_env: beta
          --database_name: glue-catalog-database
    triggers:
      website-monitoring-service:
        type: ON_DEMAND
        schedule: null
        actions:
        - job_name: website-monitoring-service
