womply-pay:
  team: app
  pagerduty_enabled: false
  slack_channel: alerts-womply-pay
  alias: app39
  topics:
    names:
    - soa-payment-settlements
  glue:
    connections:
      womply-pay-service:
        availability_zone: us-west-2c
        engine: postgresql
        port: 5432
        host: db-womplypay-preprod.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        name: service
    crawlers:
      datalake-womply-pay-service:
        connection_name: womply-pay-service
        include_path: service
        exclude_paths: []
        trigger: 'cron(30 10 * * ? *)'
    jobs:
      womply-pay-service:
        connection_name: womply-pay-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/beta/womply_pay_service.py
        python_version: 3
        number_of_workers: 10
        worker_type: Standard
        default_arguments:
          --TempDir: s3://womply-datalake-glue-working/beta/
          --conf: "spark.yarn.maxAppAttempts=1"
          --extra-py-files: s3://womply-datalake-scripts/beta/datalake-common-lib.zip
          --job-language: python
          --womply_env: beta
          --database_name: glue-catalog-database
    triggers:
      womply-pay-service:
        type: ON_DEMAND
        schedule: null
        actions:
        - job_name: womply-pay-service
