---
# The ingress rule must have any one of the parameter set: source_security_group_id, cidr_block or self
openvpn-postgres-connection:
  from_port: 5432
  protocol: tcp
  security_group_id: postgres
  source_security_group_id: legacy-vpn
  to_port: 5432
  type: ingress

glue-postgres-connection:
  from_port: 5432
  protocol: tcp
  security_group_id: postgres
  source_security_group_id: glue
  to_port: 5432
  type: ingress

ecs-prod-cluster:
  cidr_block: ["10.0.54.0/24", "10.0.24.0/24", "10.0.23.0/24"]
  from_port: 5432
  protocol: tcp
  security_group_id: postgres
  to_port: 5432
  type: ingress

ecs-prod-rds:
  from_port: 5432
  protocol: tcp
  security_group_id: postgres
  source_security_group_id: ecs-prod-rds
  to_port: 5432
  type: ingress
