---
# The ingress rule must have any one of the parameter set: source_security_group_id, cidr_block or self
openvpn-postgres-connection:
  from_port: 5432
  protocol: tcp
  security_group_id: postgres
  source_security_group_id: legacy-vpn
  to_port: 5432
  type: ingress

glue-postgres-connection:
  from_port: 5432
  protocol: tcp
  security_group_id: postgres
  source_security_group_id: glue
  to_port: 5432
  type: ingress

ecs-beta-cluster:
  cidr_block: ["10.0.49.0/24", "10.0.50.0/24", "10.0.51.0/24"]
  from_port: 5432
  protocol: tcp
  security_group_id: postgres
  to_port: 5432
  type: ingress

ecs-beta-rds:
  from_port: 5432
  protocol: tcp
  security_group_id: postgres
  source_security_group_id: ecs-beta-rds
  to_port: 5432
  type: ingress
