---
bank-account:
  team: data-platform
  pagerduty_enabled: false
  slack_channel: alerts-womply-pay
  alias: app29
  glue:
    connections:
      bank-account-service:
        name: bank_account_db
        engine: postgresql
        host: psql-bank-account-prod.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        port: 5432
        availability_zone: us-west-2b
    crawlers:
      datalake-bank-account-service:
        connection_name: bank-account-service
        include_path: bank_account_db
        exclude_paths: []
        trigger: 'cron(00 10 * * ? *)'
    jobs:
      bank-account-service:
        connection_name: bank-account-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/prod/bank_account_service.py
        python_version: 3
        worker_type: Standard
        number_of_workers: 10
        default_arguments:
          --extra-py-files: s3://womply-datalake-scripts/prod/datalake-common-lib.zip
          --TempDir: s3://womply-datalake-glue-working/prod/
          --job-language: python
          --womply_env: prod
          --database_name: glue-catalog-database
    triggers:
      bank-account-service:
        type: SCHEDULED
        schedule: 'cron(00 07 * * ? *)'
        actions:
        - job_name: bank-account-service
