---
campaign:
  team: app
  pagerduty_enabled: false
  slack_channel: alerts-apps-platform
  alias: app26
  glue:
    connections:
      campaign-service:
        name: campaign_db
        engine: postgresql
        host: psql-campaign-prod.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        port: 5432
        availability_zone: us-west-2b
    crawlers:
      datalake-campaign-service:
        connection_name: campaign-service
        include_path: campaign_db
        exclude_paths: []
        trigger: 'cron(00 06 * * ? *)'
    jobs:
      campaign-service:
        connection_name: campaign-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/prod/campaign_service.py
        python_version: 3
        worker_type: Standard
        number_of_workers: 10
        default_arguments:
          --extra-py-files: s3://womply-datalake-scripts/prod/datalake-common-lib.zip
          --TempDir: s3://womply-datalake-glue-working/prod/
          --job-language: python
          --womply_env: prod
          --database_name: glue-catalog-database
          --conf: "spark.yarn.maxAppAttempts=1"
    triggers:
      campaign-service:
        type: SCHEDULED
        schedule: 'cron(30 06 * * ? *)'
        actions:
        - job_name: campaign-service
