customer-import:
  team: app
  pagerduty_enabled: false
  slack_channel: alerts-infra
  alias: app28
  glue:
    connections:
      customer-import-service:
        name: customerimport_db
        engine: postgresql
        host: psql-customerimport-prod.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        port: 5432
        availability_zone: us-west-2a
    crawlers:
      datalake-customer-import-service:
        connection_name: customer-import-service
        include_path: customerimport_db
        exclude_paths: []
        trigger: 'cron(11 22 * * ? *)'
    jobs:
      customer-import-service:
        connection_name: customer-import-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/prod/customer_import_service.py
        python_version: 3
        number_of_workers: 10
        worker_type: 'G.1X'
        default_arguments:
          --extra-py-files: s3://womply-datalake-scripts/prod/datalake-common-lib.zip
          --TempDir: s3://womply-datalake-glue-working/prod/
          --job-language: python
          --womply_env: prod
          --database_name: glue-catalog-database
    triggers:
      customer-import-service:
        type: SCHEDULED
        schedule: 'cron(00 13 * * ? *)'
        actions:
        - job_name: customer-import-service
