---
customer-graph:
  team: app
  pagerduty_enabled: false
  slack_channel: alerts-apps-platform
  alias: svc35
  glue:
    connections:
      customer-graph-service:
        name: customergraph_db
        engine: postgresql
        host: psql-customergraph-prod.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        port: 5432
        availability_zone: us-west-2a
    crawlers:
      datalake-customer-graph-service:
        connection_name: customer-graph-service
        include_path: customergraph_db
        exclude_paths: []
        trigger: 'cron(30 08 * * ? *)'
    jobs:
      customer-graph-service:
        connection_name: customer-graph-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/prod/customer_graph_service.py
        python_version: 3
        worker_type: Standard
        number_of_workers: 10
        default_arguments:
          --extra-py-files: s3://womply-datalake-scripts/prod/datalake-common-lib.zip
          --TempDir: s3://womply-datalake-glue-working/prod/
          --job-language: python
          --womply_env: prod
          --database_name: glue-catalog-database
          --conf: "spark.yarn.maxAppAttempts=1"
    triggers:
      customer-graph-service:
        type: SCHEDULED
        schedule: 'cron(00 09 * * ? *)'
        actions:
        - job_name: customer-graph-service
