---
email:
  team: app
  pagerduty_enabled: false
  slack_channel: alerts-email-platform
  alias: svc12
  glue:
    connections:
      email-service:
        name: service
        engine: postgresql
        host: prod-svc12-postgres.ctcscgdmwqwe.us-west-2.rds.amazonaws.com
        port: 5432
        availability_zone: us-west-2c
    crawlers:
      datalake-email-service:
        connection_name: email-service
        include_path: service
        exclude_paths: []
        table_prefix: 'email_'
        trigger: 'cron(00 05 * * ? *)'
    jobs:
      email-service:
        connection_name: email-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/prod/email_service.py
        python_version: 3
        worker_type: 'G.2X'
        number_of_workers: 20
        default_arguments:
          --extra-py-files: s3://womply-datalake-scripts/prod/datalake-common-lib.zip
          --TempDir: s3://womply-datalake-glue-working/prod/
          --job-language: python
          --womply_env: prod
          --database_name: glue-catalog-database
          --conf: "spark.yarn.maxAppAttempts=1"
      email-service-emails:
        connection_name: email-service
        glue_version: '2.0'
        script_location: s3://womply-datalake-scripts/prod/email_service_emails.py
        python_version: 3
        worker_type: Standard
        number_of_workers: 10
        default_arguments:
          --extra-py-files: s3://womply-datalake-scripts/prod/datalake-common-lib.zip
          --TempDir: s3://womply-datalake-glue-working/prod/
          --job-language: python
          --womply_env: prod
          --database_name: glue-catalog-database
          --db_password_secret_id: "/apps/glue/jobs/shared/DB_PASSWORD"
          --db_user: "datalakeprod"
          --conf: "spark.yarn.executor.memoryOverhead=7168"
          --db_url: "jdbc:postgresql://prod-svc12-postgres.ctcscgdmwqwe.us-west-2.rds.amazonaws.com:5432/service"
          --num_partitions: "30"
    triggers:
      email-service:
        type: ON_DEMAND
        schedule: null
        actions:
        - job_name: email-service
        - job_name: email-service-emails
