---
file-transfer:
  team: app
  pagerduty_enabled: false
#  TODO: Enable pagerduty
  slack_channel: alerts-infra-critical
  alias: svc51
  extra-policies:
    filetransfer-cross-account:
      description: Grants file-transfer-service read write access to s3 buckets
      policy_template: s3_read_write.json.tmpl
      params:
        read_only_bucket_paths:
        - fundrocket-data/prod/document_upload/tax_document/*
        - womply-external-partners/0160/from_womply/*
        read_write_bucket_paths:
        - womply-external-partners/0153/from_womply/*
        - womply-external-partners/0160/from_womply/*
  queues:
    medium:
      receive_wait_time_seconds: 20
  topics:
    arns:
    - arn:aws:sns:us-west-2:754841671700:prod-fundrocket-data-document-uploaded
  secrets:
  - DB_PASSWORD_CRYPT
  postgres:
    index: 1
    name: 'service'
    family: 'postgres12'
    version: '12.7'
    instance_class: 'db.m5.xlarge'
    storage: 100
    apply_immediately: true
    storage_encrypted: true
    performance_insights: true
    backup_period: 30
