---
gmd-nav:
  team: app
# PagerDuty will be enabled after testing the service on beta
  pagerduty_enabled: false
  slack_channel: alerts-apps-platform
  alias: app00
  secrets:
  - CAMPAIGN_SERVICE_API_TOKEN
  - CRYPT_KEY
  - DB_PASSWORD_CRYPT
  - LOGGLY_TOKEN
  - USER_SERVICE_API_TOKEN
  postgres:
    index: 1
    name: 'gmdnav_db'
    family: 'postgres12'
    version: '12.7'
    instance_class: 'db.t2.small'
    storage_encrypted: true
    performance_insights: true
    backup_period: 7
