---
platform-real:
  team: api-platform
  pagerduty_enabled: true
  slack_channel: alerts-api
  alias: app33
  secrets:
  - INSIGHTS_SERVICE_TOKEN
  - TRANSACTION_COMPONENT_SERVICE_TOKEN
  - TRANSACTION_SERVICE_TOKEN
