---
signup:
  team: app
  slack_channel: alerts-apps-platform
  alias: app10
  amq:
    auto_minor_version_upgrade: true
    configuration: config/files/activemq.xml
    deployment_mode: SINGLE_INSTANCE
    engine_type: ActiveMQ
    engine_version: 5.15.15
    host_instance_type: mq.m5.large
    name: signup-activemq
