---
transaction-component:
  team: data-platform
  pagerduty_enabled: true
  slack_channel: alerts-payments-data
  alias: app15
  secrets:
  - ADS_SERVICE_API_TOKEN
  - APIGEE_CLIENT_API_TOKEN
  - CASSANDRA_PASSWORD
  - CUSTOMER_ENGAGEMENT_SERVICE_API_TOKEN
  - CUSTOMER_GRAPH_SERVICE_API_TOKEN
  - CUSTOMER_PROFILE_SERVICE_API_TOKEN
  - EMAIL_SERVICE_API_TOKEN
  - EXTERNAL_DATA_PROXY_SERVICE_API_TOKEN
  - JENKINS_CLIENT_API_TOKEN
  - PLATFORM_REAL_SERVICE_API_TOKEN
